### PR TITLE
v1.10

### PR DESCRIPTION
**Pull request by josteinaj**
- Modified xpath to avoid internal saxon error. closes #64
- Updated developer documentation. closes #63
- Updated dependencies. closes #52
- Also closes #53 since it's no longer needed

## depends on:
- daisy/pipeline-mod-nlp#19
- daisy/pipeline-scripts-utils#80
- daisy/pipeline-modules-common#90
- daisy/pipeline-mod-audio#16

### CODE REVIEW

**Comment by bertfrees** [comment]
In order to make the TTS modules work at all I think https://github.com/daisy/pipeline-mod-tts/issues/65 is required.

**Comment by josteinaj** [comment]
#65 seems to reference a commit on the master branch...?

**Comment by bertfrees** [comment]
Yes but that's in pipeline-mod-braille :)

**Comment by josteinaj** [comment]
Oh, I didn't notice :P.

@bertfrees Do you plan to make a v1.10 branch? Would that require any significant changes to the dependencies? Will the latest version of the generic braille scripts be part of the official DP2 v1.10 release?

**Comment by bertfrees** [comment]
I can make a v1.10 branch yes. I haven't really thought about it but I think it makes most sense to base assembly 1.10 on 1.9.10 (and not on 1.9). That means the latest version of the generic braille scripts will be part of 1.10. We could consider leaving out the unimplemented options.

There are no significant changes to the dependencies I think. Only the jStyleParser update affects the other modules AFAIK. If in order to include the latest braille modules you want me to fix #65, I'll do that.

**Comment by josteinaj** [comment]
If we need #65 to get the TTS modules as well, then it would be good to have that, yes.

**Pull request closed without merging**
